{
 "title": "Authentication service performance metrics",
 "tags": [ "chat-auth" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "description": "Displays the amount of requests per second processed by the application",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{http_server_name='auth_backend'}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Displays latency for 95/99% of requests processed by the application in ms.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_milliseconds_bucket{http_server_name='auth_backend'}[1m])))",
     "legendFormat": "Latency for 95% of requests"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(http_server_duration_milliseconds_bucket{http_server_name='auth_backend'}[1m])\n  )\n)",
     "legendFormat": "Latency for 99% of requests"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "The amount of requests that has been responded with 4xx or 5xx status codes.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(http_server_duration_milliseconds_count{http_status_code=~'4..', http_server_name='auth_backend'}[$__rate_interval])",
     "legendFormat": "4xx status code"
    },
    {
     "expr": "increase(http_server_duration_milliseconds_count{http_status_code=~'5..', http_server_name='auth_backend'}[$__rate_interval])",
     "legendFormat": "5xx status codes"
    }
   ]
  }
 ]
}