{
 "title": "Transportation service performance",
 "description": "The vital metrics of the transportation service.",
 "tags": [ "chat-transportation" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "description": "The amount of requests that the application processes per second.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{http_server_name='transportation_backend'}[$__rate_interval]))",
     "legendFormat": "Rps"
    }
   ]
  },
  {
   "title": "Websocket hub active connections",
   "type": "timeseries",
   "description": "The amount of connections to the websocket hub.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "websocket_hub_active_connections",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "The amount of the requests that has been responded with 4xx or 5xx status codes.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "increase(http_server_duration_milliseconds_count{http_status_code=~'4..', http_server_name='transportation_backend'}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(http_server_duration_milliseconds_count{http_status_code=~'5..', http_server_name='transportation_backend'}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "The latency of 95/99% requests.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(http_server_duration_milliseconds_bucket{http_server_name='transportation_backend'}[1m])\n  )\n)",
     "legendFormat": "Latency for 95% of requests"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(http_server_duration_milliseconds_bucket{http_server_name='transportation_backend'}[1m])\n  )\n)",
     "legendFormat": "Latency for 99% of requests"
    }
   ]
  }
 ]
}